name: smart_home
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ez_mqtt_client: ^0.0.2+2
  fluttertoast: ^7.1.6
  flutter_staggered_grid_view: ^0.3.4
  google_maps_flutter: ^2.0.1
  google_map_location_picker: ^4.1.7
  date_time_picker: "^2.0.0"
  flutter_webview_plugin: ^0.3.11
  android_alarm_manager: ^2.0.0
  flutter_local_notifications:
  flutter_ringtone_player: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/
  uses-material-design: true